fix
Signed-off-by: Yashvardhan Kukreja <yashvardhan@oplabs.co>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -54,7 +54,6 @@ orbs:
   slack: circleci/slack@4.10.1
   shellcheck: circleci/shellcheck@3.2.0
   codecov: codecov/codecov@5.0.3
-  utils: yashvardhan-kukreja/circleci-utils@1.0.8
 
 commands:
   gcp-oidc-authenticate:
@@ -163,6 +162,158 @@ commands:
           environment:
             FOUNDRY_PROFILE: ci
 
+  setup-circleci-utils-and-github-token:
+    description: >
+      This command will take care to setup the circleci-utils. This will run only once per job.
+    parameters:
+      circleci-utils-tag:
+        type: string
+        default: "v0.5.0"
+        description: "The version of the circleci-utils to use"
+      private-key-str:
+        type: env_var_name
+        default: GITHUB_APP_KEY
+        description: "The GitHub App's private key"
+      app-id:
+        type: env_var_name
+        default: GITHUB_APP_ID
+        description: "The GitHub App ID"
+      github-token:
+        type: env_var_name
+        default: GITHUB_TOKEN_GOVERNANCE
+        description: "The GitHub token"
+      github-app-repo:
+        type: string
+        description: "The repository to get the token for"
+        default: "$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME"
+      condition:
+        type: string
+        default: "always"
+        description: "The condition to run the command. 0 and always are considered true, everything else is false"
+    steps:
+      - run:
+          name: Setup circleci-utils
+          command: |
+            if [ "<< parameters.condition >>" != "always" ] && [ "<< parameters.condition >>" != "0" ]; then
+              echo "Skipping command because condition is not met"
+              exit 0
+            fi
+
+            #only clone if the directory does not exist
+            if [ ! -d "/tmp/circleci-utils" ]; then
+              git clone --branch << parameters.circleci-utils-tag >> --depth 1 https://github.com/ethereum-optimism/circleci-utils.git /tmp/circleci-utils
+              GITHUB_CLI_PATH="/tmp/circleci-utils/github_utility/github_cli"
+              CIRCLECI_TOOLS_PATH=$GITHUB_CLI_PATH/main.py
+
+              cd $(dirname "$CIRCLECI_TOOLS_PATH")
+              pip install -r requirements.txt
+
+              echo "export CIRCLECI_TOOLS_PATH=$CIRCLECI_TOOLS_PATH" >> $BASH_ENV
+
+            fi
+
+            cd $(dirname "$CIRCLECI_TOOLS_PATH")
+
+            # if SECRET_ACCESS_TOKEN_FILE_PATH is set, we are already done
+            if [ -f "$SECRET_ACCESS_TOKEN_FILE_PATH" ]; then
+              echo "Secret Access Token File is already set in $SECRET_ACCESS_TOKEN_FILE_PATH"
+              exit 0
+            fi
+
+            # we create a temp random file name to store the token in
+            SECRET_ACCESS_TOKEN_FILE_PATH=$(mktemp)
+            echo "export SECRET_ACCESS_TOKEN_FILE_PATH=$SECRET_ACCESS_TOKEN_FILE_PATH" >> $BASH_ENV
+
+
+            echo "Token not set in $SECRET_ACCESS_TOKEN_FILE_PATH"
+            #get the token
+
+            # we give priority to the github-token parameter if set
+
+            if [ -n "${<< parameters.github-token >>}" ]; then
+              echo "Using github-token parameter"
+              token="${<< parameters.github-token >>}"
+            else
+              echo "Using private-key-str parameter"
+              token=$(python $CIRCLECI_TOOLS_PATH get-github-access-token --private-key-str="${<< parameters.private-key-str >>}" --app-id="${<< parameters.app-id >>}" --repo "<< parameters.github-app-repo >>")
+            fi
+
+            echo ${token} > $SECRET_ACCESS_TOKEN_FILE_PATH
+
+            #if the token is not set, fail the build
+            if [ -z "${token}" ]; then
+              echo "Failed to get GitHub Access Token"
+              exit 1
+            else
+              echo "Successfully got GitHub Access Token"
+            fi
+
+  checkout-with-mise:
+    description: >
+      Checkout then initialize the mise environment.
+    steps:
+      - checkout
+      - run:
+          name: Initialize mise environment
+          command: |
+            # This is used to create a per-user cache key to preserve permissions across different
+            # executor types.
+            user=$(whoami)
+            echo "$user" > .executor-user
+            echo "Set executor user to $user."
+
+            if [[ "$user" == "root" ]]; then
+              # Self-hosted runners will persist this cache between runs. Cleaning it up means that we
+              # preserve the semantics of the cache regardless of executor type. It's also much faster
+              # to delete the cache and recreate it than it is to overwrite it in place.
+              rm -rf /data/mise-data
+              echo "Cleaned up cache data."
+
+              mkdir -p /data/mise-data
+              echo "Created Mise data dir."
+              mkdir -p ~/.cache
+              echo "Created Mise cache dir."
+            else
+              sudo rm -rf /data/mise-data
+              echo "Cleaned up cache data."
+              sudo mkdir -p /data/mise-data
+              sudo chown -R "$user:$user" /data/mise-data
+              echo "Created Mise data dir."
+              sudo mkdir -p ~/.cache
+              sudo chown -R "$user:$user" ~/.cache
+              echo "Created Mise cache dir."
+            fi
+      - restore_cache:
+          name: Restore mise cache
+          keys:
+            - mise-v5-{{ checksum ".executor-user" }}-{{ checksum "mise.toml" }}
+      - run:
+          name: Install mise
+          command: |
+            if command -v mise &> /dev/null; then
+              echo "mise already installed at $(command -v mise)"
+            else
+              curl https://mise.run | sh
+            fi
+
+            echo "export PATH=\"$HOME/.local/bin:\$PATH\"" >> "$BASH_ENV"
+            echo "export MISE_DATA_DIR=/data/mise-data" >> "$BASH_ENV"
+            echo "export MISE_JOBS=$(nproc)" >> "$BASH_ENV"
+            echo "eval \"\$($HOME/.local/bin/mise activate --shims)\"" >> "$BASH_ENV"
+      - run:
+          name: Install mise deps
+          command: |
+            mise install -v -y
+      - save_cache:
+          name: Save mise cache
+          key: mise-v5-{{ checksum ".executor-user" }}-{{ checksum "mise.toml" }}
+          paths:
+            - /data/mise-data
+      - run:
+          name: Delete executor file
+          command: |
+            rm -f .executor-user
+
 jobs:
   cannon-go-lint-and-test:
     machine: true
@@ -179,7 +330,7 @@ jobs:
         type: integer
         default: 32
     steps:
-      - utils/checkout-with-mise
+      - checkout-with-mise
       - check-changed:
           patterns: cannon,packages/contracts-bedrock/src/cannon,op-preimage,go.mod
       - attach_workspace:
@@ -252,7 +403,7 @@ jobs:
       - image: <<pipeline.parameters.default_docker_image>>
     resource_class: large
     steps:
-      - utils/checkout-with-mise
+      - checkout-with-mise
       - check-changed:
           patterns: cannon/mipsevm/tests/open_mips_tests/test
       - run:
@@ -271,7 +422,7 @@ jobs:
     machine: true
     resource_class: ethereum-optimism/latitude-1
     steps:
-      - utils/checkout-with-mise
+      - checkout-with-mise
       - run:
           name: Check `RISCV.sol` bytecode
           working_directory: packages/contracts-bedrock
@@ -320,7 +471,7 @@ jobs:
         type: string
         default: ci
     steps:
-      - utils/checkout-with-mise
+      - checkout-with-mise
       - install-contracts-dependencies
       - run:
           name: Print forge version
@@ -350,7 +501,7 @@ jobs:
       - image: <<pipeline.parameters.default_docker_image>>
     resource_class: xlarge
     steps:
-      - utils/checkout-with-mise
+      - checkout-with-mise
       - attach_workspace: { at: "." }
       - install-contracts-dependencies
       - check-changed:
@@ -411,7 +562,7 @@ jobs:
       resource_class: "<<parameters.resource_class>>"
       docker_layer_caching: true # we rely on this for faster builds, and actively warm it up for builds with common stages
     steps:
-      - utils/checkout-with-mise
+      - checkout-with-mise
       - attach_workspace:
           at: /tmp/docker_images
       - run:
@@ -608,7 +759,7 @@ jobs:
     machine: true
     resource_class: ethereum-optimism/latitude-1
     steps:
-      - utils/checkout-with-mise
+      - checkout-with-mise
       - attach_workspace: { at: "." }
       - install-contracts-dependencies
       - check-changed:
@@ -672,7 +823,7 @@ jobs:
         type: string
         default: ci
     steps:
-      - utils/checkout-with-mise
+      - checkout-with-mise
       - attach_workspace: { at: "." }
       - install-contracts-dependencies
       - run:
@@ -751,7 +902,7 @@ jobs:
         type: string
         default: ci
     steps:
-      - utils/checkout-with-mise
+      - checkout-with-mise
       - attach_workspace: { at: "." }
       - install-contracts-dependencies
       - check-changed:
@@ -810,7 +961,7 @@ jobs:
       - image: <<pipeline.parameters.default_docker_image>>
     resource_class: large
     steps:
-      - utils/checkout-with-mise
+      - checkout-with-mise
       - attach_workspace: { at: "." }
       - install-contracts-dependencies
       - check-changed:
@@ -873,7 +1024,7 @@ jobs:
     machine: true
     resource_class: ethereum-optimism/latitude-1
     steps:
-      - utils/checkout-with-mise
+      - checkout-with-mise
       - attach_workspace: { at: "." }
       - install-contracts-dependencies
       - check-changed:
@@ -914,7 +1065,7 @@ jobs:
     machine:
       image: <<pipeline.parameters.base_image>>
     steps:
-      - utils/checkout-with-mise
+      - checkout-with-mise
       - run:
           name: Install ripgrep
           command: sudo apt-get install -y ripgrep
@@ -939,7 +1090,7 @@ jobs:
       - image: <<pipeline.parameters.default_docker_image>>
     resource_class: xlarge
     steps:
-      - utils/checkout-with-mise
+      - checkout-with-mise
       - check-changed:
           patterns: "<<parameters.package_name>>"
       - attach_workspace:
@@ -964,7 +1115,7 @@ jobs:
     machine: true
     resource_class: ethereum-optimism/latitude-1
     steps:
-      - utils/checkout-with-mise
+      - checkout-with-mise
       - run:
           name: run Go linter
           command: |
@@ -1003,7 +1154,7 @@ jobs:
     machine: true
     resource_class: <<parameters.resource_class>>
     steps:
-      - utils/checkout-with-mise
+      - checkout-with-mise
       - attach_workspace:
           at: "."
       - run:
@@ -1074,7 +1225,7 @@ jobs:
       - image: <<pipeline.parameters.default_docker_image>>
     resource_class: large
     steps:
-      - utils/checkout-with-mise
+      - checkout-with-mise
       - run:
           name: Install tools
           command: |
@@ -1096,7 +1247,7 @@ jobs:
     machine: true
     resource_class: ethereum-optimism/latitude-1
     steps:
-      - utils/checkout-with-mise
+      - checkout-with-mise
       - restore_cache:
           name: Restore cannon prestate cache
           key: cannon-prestate-{{ checksum "./cannon/bin/cannon" }}-{{ checksum "op-program/bin/op-program-client.elf" }}
@@ -1121,7 +1272,7 @@ jobs:
     docker:
       - image: <<pipeline.parameters.default_docker_image>>
     steps:
-      - utils/checkout-with-mise
+      - checkout-with-mise
       - setup_remote_docker
       - run:
           name: Build prestates
@@ -1136,7 +1287,7 @@ jobs:
     machine: true
     resource_class: ethereum-optimism/latitude-1
     steps:
-      - utils/checkout-with-mise
+      - checkout-with-mise
       - attach_workspace:
           at: "."
       - gcp-cli/install
@@ -1181,7 +1332,7 @@ jobs:
     docker:
       - image: <<pipeline.parameters.default_docker_image>>
     steps:
-      - utils/checkout-with-mise
+      - checkout-with-mise
       - setup_remote_docker
       - run: make -C op-program verify-reproducibility
       - notify-failures-on-develop:
@@ -1191,7 +1342,7 @@ jobs:
     docker:
       - image: <<pipeline.parameters.default_docker_image>>
     steps:
-      - utils/checkout-with-mise
+      - checkout-with-mise
       - setup_remote_docker
       - run:
           name: Build cannon
@@ -1258,7 +1409,7 @@ jobs:
     docker:
       - image: cimg/go:1.21
     steps:
-      - utils/checkout-with-mise
+      - checkout-with-mise
       - run:
           name: verify-sepolia
           command: |
@@ -1271,7 +1422,7 @@ jobs:
     machine: true
     resource_class: ethereum-optimism/latitude-1
     steps:
-      - utils/checkout-with-mise
+      - checkout-with-mise
       - run:
           name: compat-sepolia
           command: |
@@ -1282,7 +1433,7 @@ jobs:
     machine: true
     resource_class: ethereum-optimism/latitude-1
     steps:
-      - utils/checkout-with-mise
+      - checkout-with-mise
       - check-changed:
           patterns: op-node
       - run:
@@ -1293,7 +1444,7 @@ jobs:
     machine: true
     resource_class: ethereum-optimism/latitude-1
     steps:
-      - utils/checkout-with-mise
+      - checkout-with-mise
       - check-changed:
           patterns: op-service
       - run:
@@ -1305,7 +1456,7 @@ jobs:
       - image: <<pipeline.parameters.default_docker_image>>
     resource_class: xlarge
     steps:
-      - utils/checkout-with-mise
+      - checkout-with-mise
       - install-contracts-dependencies
       - check-changed:
           no_go_deps: "true"
@@ -1342,7 +1493,7 @@ jobs:
           oidc_token_file_path: /tmp/oidc_token.json
           project_id: GCP_TOOLS_ARTIFACTS_PROJECT_ID
           service_account_email: GCP_CONTRACTS_PUBLISHER_SERVICE_ACCOUNT_EMAIL
-      - utils/checkout-with-mise
+      - checkout-with-mise
       - install-contracts-dependencies
       - run:
           name: Pull artifacts
@@ -1381,7 +1532,7 @@ jobs:
       - gcp-oidc-authenticate:
           gcp_cred_config_file_path: /tmp/gcp_cred_config.json
           oidc_token_file_path: /tmp/oidc_token.json
-      - utils/checkout-with-mise
+      - checkout-with-mise
       - run:
           name: Configure Docker
           command: |
@@ -1389,7 +1540,7 @@ jobs:
       - when:
           condition: << parameters.brew_release >>
           steps:
-            - utils/setup-circleci-utils-and-github-token:
+            - setup-circleci-utils-and-github-token:
                 # GoReleaser uses the GITHUB_TOKEN environment variable to authenticate with GitHub
                 github-app-repo: ethereum-optimism/homebrew-tap
                 github-token: GITHUB_TOKEN
